CREATE TYPE "public"."free_story_status" AS ENUM('active', 'draft');--> statement-breakpoint
CREATE TABLE "free_stories" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"status" "free_story_status" DEFAULT 'draft' NOT NULL,
	"title" text,
	"summary" text,
	"text" text NOT NULL,
	"theme" text NOT NULL,
	"mood" text NOT NULL,
	"length" text NOT NULL,
	"lesson" text,
	"setting" text,
	"conflict" text,
	"tone" text,
	"audio_url" text,
	"audio_status" text DEFAULT 'none' NOT NULL,
	"audio_error" text,
	"audio_voice_id" text,
	"audio_preset" text,
	"audio_updated_at" timestamp with time zone,
	"audio_hash" text,
	"audio_character_count" integer,
	"cover_url" text,
	"cover_square_url" text,
	"cover_status" text DEFAULT 'none' NOT NULL,
	"cover_error" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"published_at" timestamp with time zone
);
